#!/usr/bin/env python3
"""Batch application generator + sender.

Reads jobs from a JSON file, generates tailored CV + cover letter for each,
compiles PDFs, and sends emails via Gmail SMTP.

Usage:
  python scripts/batch_apply.py --jobs data/new_jobs.json --dry-run
  python scripts/batch_apply.py --jobs data/new_jobs.json --send --delay 2
"""
import argparse
import json
import os
import random
import smtplib
import subprocess
import sys
import time
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from pathlib import Path

# Setup env
sys.path.insert(0, str(Path(__file__).resolve().parent))
from env_loader import load_env
load_env()
from profile_loader import PROFILE, get_sender

SENDER = get_sender()
CV_DIR = Path(__file__).parent.parent / "cv"
COVER_DIR = Path(__file__).parent.parent / "cover_letters"
SENT_LOG = Path(__file__).parent.parent / "data" / "batch_sent.json"

# Candidate profile (constant across all applications)
CANDIDATE = {
    "name": PROFILE.get("name", "Your Name"),
    "address": "Resistencia, Chaco, Argentina",
    "phone": PROFILE.get("phone", "+00 0 000 000000"),
    "email": PROFILE.get("email", "you@example.com"),
    "linkedin": PROFILE.get("linkedin", "linkedin.com/in/your-handle"),
    "github": PROFILE.get("github", "github.com/your-username"),
    "portfolio": PROFILE.get("portfolio", "your-portfolio.example.com"),
}


def generate_cv_tex(job: dict, output_path: Path) -> None:
    """Generate a tailored CV .tex file."""
    company = job.get("company", "the team")
    role = job.get("title", "Developer")
    # Sanitize filenames
    safe_name = "".join(c if c.isalnum() else "_" for c in f"{company}_{role}").lower()[:50]

    tex = r"""%% CV - Mario Aquino
%% Target: {role} @ {company}
%% Auto-generated by batch_apply.py

\documentclass[11pt,a4paper,sans]{{moderncv}}
\moderncvstyle{{banking}}
\moderncvcolor{{blue}}

\renewcommand*\firstnamestyle[1]{{{{\fontsize{{34}}{{36}}\bfseries\upshape\color{{color1}}#1}}}}
\renewcommand*\lastnamestyle[1]{{{{\fontsize{{34}}{{36}}\bfseries\upshape\color{{color1}}#1}}}}
\renewcommand*\sectionstyle[1]{{{{\sectionfont\color{{color1}}#1}}}}

\usepackage[utf8]{{inputenc}}
\usepackage{{needspace}}
\usepackage{{hyperref}}
\hypersetup{{
    colorlinks=true,
    linkcolor=blue,
    filecolor=magenta,
    urlcolor=blue,
    pdftitle={{Mario Aquino - CV}},
    pdfpagemode=FullScreen,
}}
\usepackage[scale=0.77]{{geometry}}

\name{{Mario}}{{Aquino}}
\address{{Resistencia, Chaco, Argentina}}{{Open to Remote / Relocation}}{{}}
\phone[mobile]{{{phone}}}
\email{{{email}}}
\extrainfo{{\href{{https://{linkedin}}}{{LinkedIn}}, \href{{https://{github}}}{{GitHub}}, \href{{https://{portfolio}}}{{Portfolio}}}}

\begin{{document}}

\makecvtitle

\vspace{{6pt}}
\small{{Full-stack developer with 5+ years building web applications end to end: React and Next.js frontends with Tailwind CSS and shadcn/ui, Node.js and Python backends, REST APIs and cloud-native infrastructure on AWS and Vercel. AI-native workflow: integrates LLMs and prompt engineering into shipped products, builds with \textbf{{Claude Code}}, and designs with UX, accessibility and performance in mind. Mentor-led, autonomous, and comfortable owning projects from day one.}}

\section{{Core Competencies}}
\vspace{{1pt}}
\begin{{itemsize}}

\item \textbf{{Frontend}}: React.js, Next.js, JavaScript/TypeScript, HTML5, CSS3, Tailwind CSS, shadcn/ui, Framer Motion; reusable UI libraries that accelerated delivery by 30\%, accessibility work that raised Lighthouse scores by 30+ points.

\item \textbf{{Backend}}: Node.js (NestJS, Express), Python (FastAPI/Django), REST APIs, microservices; Supabase/Firebase-style backends (quick ramp-up).

\item \textbf{{AI and automation}}: LLM orchestration (LangChain, Ollama self-hosted), multi-agent systems, prompt engineering, n8n process automation; develops with \textbf{{Claude Code}}.

\item \textbf{{Cloud and tooling}}: Vercel, AWS (EC2, S3, Lambda), Docker, Git, CI/CD with GitHub Actions; agile delivery.

\end{{itemsize}}

\section{{Professional Experience}}
\vspace{{3pt}}
\begin{{itemsize}}

\needspace{{5\baselineskip}}
\item{{\cventry{{2026--Present}}{{Scraper Developer (part-time)}}{{Magnar}}{{Remote, Chile}}{{}}{{\vspace{{1pt}}
\begin{{itemize}}
    \item Build and maintain Python/Node data-extraction services collecting public legal documents.
    \item Deliver normalized, structured data feeding an LLM-based legal platform.
\end{{itemsize}}}}}}

\vspace{{3pt}}

\needspace{{5\baselineskip}}
\item{{\cventry{{2024--2026}}{{Senior Full-Stack Engineer}}{{SalesMatch.Ai}}{{Remote, Spain}}{{}}{{\vspace{{1pt}}
\begin{{itemize}}
    \item Architected and maintained scalable backend services in Node.js, TypeScript and NestJS.
    \item Cut deployment time by 50\% by optimizing GitHub Actions CI/CD pipelines.
    \item Built internal automation workflows with Python and n8n.
    \item Designed AWS infrastructure strategy around Docker and Kubernetes.
\end{{itemsize}}}}}}

\vspace{{3pt}}

\needspace{{5\baselineskip}}
\item{{\cventry{{2023--2024}}{{Full-Stack Developer}}{{Syloper}}{{Santa Fe, Argentina}}{{}}{{\vspace{{1pt}}
\begin{{itemize}}
    \item Built high-performance web applications with React, Next.js and Node.js.
    \item Improved API response times by 45\% through PostgreSQL and Redis query optimization.
    \item Created a reusable UI component library, accelerating frontend delivery by 30\%.
\end{{itemsize}}}}}}

\vspace{{3pt}}

\needspace{{5\baselineskip}}
\item{{\cventry{{2023--2024}}{{Software Engineer}}{{FlamaTech}}{{Remote, Spain}}{{}}{{\vspace{{1pt}}
\begin{{itemize}}
    \item Designed and documented comprehensive REST APIs, reducing cross-team integration issues by 40\%.
    \item Refactored critical legacy modules with Clean Architecture (SOLID, DDD).
    \item Implemented automated Jest test suites, increasing system stability by 30\%.
\end{{itemsize}}}}}}

\vspace{{3pt}}

\needspace{{5\baselineskip}}
\item{{\cventry{{2022--2023}}{{Programming Coach and Mentor}}{{Kodigo}}{{Remote, El Salvador}}{{}}{{\vspace{{1pt}}
\begin{{itemize}}
    \item Taught full-stack development to 150+ students with a 92\% satisfaction rate.
    \item Improved student retention by 30\% through personalized technical mentoring.
\end{{itemsize}}}}}}

\vspace{{3pt}}

\needspace{{5\baselineskip}}
\item{{\cventry{{2021--2022}}{{Frontend Development Intern}}{{AirBits}}{{Argentina}}{{}}{{\vspace{{1pt}}
\begin{{itemize}}
    \item Shipped UI/UX improvements that reduced user friction by 25\%.
    \item Applied web accessibility (A11y) best practices, raising Lighthouse scores by 30+ points.
\end{{itemsize}}}}}}

\end{{itemsize}}

\section{{Selected Projects}}
\vspace{{1pt}}
\begin{{itemize}}

\item \textbf{{Kosame (AI + automation)}}: voice-to-user-story generator built on LLMs, integrated with Trello and n8n; multi-agent workflows on self-hosted Ollama models.
\href{{https://github.com/Marigiko}}{{(GitHub)}}

\item \textbf{{Real-Time IoT Monitoring Platform}}: event-driven system in Node.js processing device data over MQTT and Kafka; AWS provisioned with Terraform, microservices on Kubernetes/Helm.

\item \textbf{{GeoPlanning TTFS}}: React dashboard for FTTH network planning with geo-spatial visualization.

\end{{itemsize}}

\section{{Education}}
\vspace{{1pt}}
\begin{{itemize}}

\item{{\cventry{{In progress}}{{Information Systems Engineering}}{{National Technological University (UTN)}}{{Argentina}}{{}}{{}}}}

\vspace{{3pt}}

\item{{\cventry{{In progress}}{{Bachelor's in Cyber Defense}}{{National University of Defense (UNDEF)}}{{Argentina}}{{}}{{}}}}

\end{{itemsize}}

\section{{Languages}}
\vspace{{1pt}}
\begin{{itemize}}
\item Spanish (native), English (B2+, professional working), Portuguese (B2).
\end{{itemsize}}

\section{{Certifications}}
\vspace{{1pt}}
\begin{{itemize}}
\item Scrum Developer Professional (SDPC) and Scrum Fundamentals (SFPC), SCRUMstudy; Python Essentials (Cisco/NDG); Python, SQL, JavaScript and Problem Solving (HackerRank); Argentina Programa (2022).
\end{{itemsize}}

\section{{References}}
\vspace{{1pt}}
\begin{{itemize}}
\item{{Available upon request.}}
\end{{itemsize}}

\end{{document}}
""".replace("{role}", role).replace("{company}", company).replace("{phone}", CANDIDATE["phone"]).replace("{email}", CANDIDATE["email"]).replace("{linkedin}", CANDIDATE["linkedin"]).replace("{github}", CANDIDATE["github"]).replace("{portfolio}", CANDIDATE["portfolio"]).replace("{{", "{").replace("}}", "}")

    output_path.write_text(tex, encoding="utf-8")


def escape_latex(text: str) -> str:
    """Escape special LaTeX characters in text."""
    # Use a placeholder for backslash to avoid double-escaping
    text = text.replace('\x00', '')  # remove any null chars first
    # Replace backslash with placeholder first, then restore at the end
    text = text.replace('\\', '\x00BS\x00')
    replacements = [
        ('%', r'\%'),
        ('&', r'\&'),
        ('_', r'\_'),
        ('#', r'\#'),
        ('$', r'\$'),
        ('{', r'\{'),
        ('}', r'\}'),
        ('~', r'\textasciitilde{}'),
        ('^', r'\textasciicircum{}'),
    ]
    for char, replacement in replacements:
        text = text.replace(char, replacement)
    # Restore backslash last
    text = text.replace('\x00BS\x00', r'\textbackslash{}')
    return text


def generate_cover_tex(job: dict, output_path: Path) -> None:
    """Generate a tailored cover letter .tex file."""
    company = escape_latex(job.get("company", "the team"))
    role = escape_latex(job.get("title", "Developer"))
    location = job.get("location", "")
    description = job.get("description", "")

    # Build a short tailored hook based on available info
    hook = f"Me postulo a la posicion de {role}."
    if "IA" in description or "LLM" in description or "AI" in description or "agent" in description.lower():
        hook += " Llevo mas de cinco anos construyendo aplicaciones web end to end y, especialmente, integrando IA en productos reales: orquestacion de LLM, RAG y flujos multi-agente."
    elif "backend" in role.lower() or "Backend" in description:
        hook += " Llevo mas de cinco anos disenando y construyendo APIs y servicios backend escalables con Node.js, Python y arquitecturas cloud-native."
    elif "frontend" in role.lower() or "Frontend" in description:
        hook += " Llevo mas de cinco anos construyendo interfaces web de alto rendimiento con React, Next.js y Tailwind CSS, con foco en accesibilidad y UX."
    elif "fullstack" in role.lower().replace(" ", "") or "full stack" in role.lower():
        hook += " Llevo mas de cinco anos construyendo aplicaciones web end to end con React, Next.js, Node.js y Python, y me interesa especialmente integrar IA desde el primer dia."
    else:
        hook += " Llevo mas de cinco anos construyendo aplicaciones web end to end con React, Next.js, Node.js y Python, y me interesa especialmente integrar IA en productos reales."

    tex = r"""%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Cover Letter - {company}, {role}
% Auto-generated by batch_apply.py
% Compile with: xelatex {output_name}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\documentclass{{cover}}
\usepackage{{fancyhdr}}

\pagestyle{{fancy}}
\fancyhf{{}}

\rfoot{{Page \thepage \hspace{{0pt}}}}
\thispagestyle{{empty}}
\renewcommand{{\headrulewidth}}{{0pt}}
\begin{{document}}

\namesection{{}}{{\Huge{{{name}}}}}{{  \href{{mailto:{email}}}{{{email}}} | {phone} |  \urlstyle{{same}}\href{{https://www.linkedin.com/in/{linkedin_handle}}}{{LinkedIn}}
}}

\currentdate{{{date}}}
\lettercontent{{Estimado equipo de {company},}}

\lettercontent{{{hook}}}

\lettercontent{{Lo que puedo aportar:}}

{{\raggedright\fontspec[Path = OpenFonts/fonts/raleway/]{{Raleway-Medium}}\fontsize{{11pt}}{{13pt}}\selectfont
\begin{{itemize}}
    \item \textbf{{Frontend con React y Next.js:}} construi aplicaciones web de alto rendimiento y una libreria de componentes reutilizable que acelero un 30\% la entrega de frontend, con accesibilidad (A11y) que subio mas de 30 puntos las metricas de Lighthouse.
    \item \textbf{{Backend y APIs:}} diseñe y documente APIs REST que redujeron un 40\% los problemas de integracion entre equipos, y mejore un 45\% los tiempos de respuesta optimizando PostgreSQL y Redis.
    \item \textbf{{IA en produccion:}} orquestacion de LLM (LangChain, Ollama self-hosted), flujos multi-agente y automatizaciones en n8n; construyo con \textbf{{Claude Code}} y reviso lo que genera antes de integrarlo.
    \item \textbf{{Despliegue:}} Vercel, AWS, Docker, CI/CD con GitHub Actions.
\end{{itemize}}\par}}
\vspace{{6pt}}

\lettercontent{{Sobre tecnologias especificas del stack: si bien no he usado todas en produccion, mi experiencia con arquitecturas similares (Firebase/Supabase, microservicios, colas) me permite ramp-up rapido. Si el equipo valora criterio tecnico, autonomia y ganas de crecer por encima de los años de experiencia, encajo sin friccion.}}

\lettercontent{{Expectativa salarial: 2000 a 3000 USD mensuales netos, en modalidad remota.}}

\lettercontent{{Quedo a disposicion para conversar.}}

\begin{{flushright}}
\closing{{Saludos cordiales,}}

\signature{{Mario Aquino}}
\end{{flushright}}
\end{{document}}
""".replace("{company}", company).replace("{role}", role).replace("{output_name}", output_path.stem).replace("{date}", time.strftime("%d de %B de %Y")).replace("{hook}", hook).replace("{{", "{").replace("}}", "}").replace("{phone}", CANDIDATE["phone"]).replace("{email}", CANDIDATE["email"]).replace("{name}", CANDIDATE["name"]).replace("{linkedin}", CANDIDATE["linkedin"]).replace("{github}", CANDIDATE["github"]).replace("{portfolio}", CANDIDATE["portfolio"]).replace("{linkedin_handle}", CANDIDATE["linkedin"].rsplit("/", 1)[-1])

    output_path.write_text(tex, encoding="utf-8")


def compile_cv(tex_path: Path) -> Path:
    """Compile CV with lualatex. Returns PDF path."""
    pdf_path = tex_path.with_suffix(".pdf")
    result = subprocess.run(
        ["lualatex", "-interaction=nonstopmode", tex_path.name],
        cwd=tex_path.parent,
        capture_output=True,
        text=True,
        timeout=120,
    )
    if result.returncode != 0:
        print(f"  [WARN] lualatex returned {result.returncode} for {tex_path.name}")
        print(f"  stderr: {result.stderr[-500:]}")
    return pdf_path


def compile_cover(tex_path: Path) -> Path:
    """Compile cover letter with xelatex. Returns PDF path."""
    pdf_path = tex_path.with_suffix(".pdf")
    result = subprocess.run(
        ["xelatex", "-interaction=nonstopmode", tex_path.name],
        cwd=tex_path.parent,
        capture_output=True,
        text=True,
        timeout=120,
    )
    if result.returncode != 0:
        print(f"  [WARN] xelatex returned {result.returncode} for {tex_path.name}")
        print(f"  stderr: {result.stderr[-500:]}")
    return pdf_path


def send_application(to_email: str, cv_pdf: Path, cover_pdf: Path, job: dict) -> bool:
    """Send application email with CV + cover letter attached."""
    password = os.getenv("GMAIL_APP_PASSWORD")
    if not password:
        raise ValueError("GMAIL_APP_PASSWORD not set in .env")

    company = job.get("company", "the team")
    role = job.get("title", "Developer")

    msg = MIMEMultipart()
    msg["From"] = SENDER
    msg["To"] = to_email
    msg["Subject"] = f"Postulacion: {role} — Mario Aquino"

    body = f"""Estimado equipo,

Adjunto mi CV y carta de presentacion para la posicion.

Quedo a disposicion para conversar.

Saludos cordiales,
{CANDIDATE['name']}
{CANDIDATE['email']}
{CANDIDATE['phone']}
{CANDIDATE['linkedin']}
"""
    msg.attach(MIMEText(body, "plain"))

    for pdf_path in [cv_pdf, cover_pdf]:
        if pdf_path.exists():
            with open(pdf_path, "rb") as f:
                part = MIMEBase("application", "octet-stream")
                part.set_payload(f.read())
            encoders.encode_base64(part)
            part.add_header("Content-Disposition", f"attachment; filename={pdf_path.name}")
            msg.attach(part)

    with smtplib.SMTP("smtp.gmail.com", 587) as server:
        server.ehlo()
        server.starttls()
        server.login(SENDER, password)
        server.send_message(msg)

    return True


def load_sent_log() -> dict:
    """Load sent log to avoid duplicates."""
    if SENT_LOG.exists():
        return json.loads(SENT_LOG.read_text(encoding="utf-8"))
    return {}


def save_sent_log(log: dict):
    """Save sent log."""
    SENT_LOG.parent.mkdir(parents=True, exist_ok=True)
    SENT_LOG.write_text(json.dumps(log, ensure_ascii=False, indent=2), encoding="utf-8")


def main():
    ap = argparse.ArgumentParser(description="Batch application generator + sender")
    ap.add_argument("--jobs", required=True, help="Path to jobs JSON file")
    ap.add_argument("--dry-run", action="store_true", help="Generate only, do not send")
    ap.add_argument("--send", action="store_true", help="Generate and send emails")
    ap.add_argument("--delay", type=int, default=3, help="Delay between emails in minutes (default 3)")
    ap.add_argument("--limit", type=int, default=0, help="Max jobs to process (0=all)")
    ap.add_argument("--offset", type=int, default=0, help="Skip first N jobs")
    args = ap.parse_args()

    jobs_path = Path(args.jobs)
    if not jobs_path.exists():
        print(f"[!] Jobs file not found: {jobs_path}")
        sys.exit(1)

    jobs_data = json.loads(jobs_path.read_text(encoding="utf-8"))
    jobs = jobs_data if isinstance(jobs_data, list) else jobs_data.get("jobs", [])

    if args.offset:
        jobs = jobs[args.offset:]
    if args.limit:
        jobs = jobs[:args.limit]

    sent_log = load_sent_log()
    print(f"\n{'='*60}")
    print(f"BATCH APPLY — {len(jobs)} jobs")
    print(f"Mode: {'DRY RUN' if args.dry_run else 'SEND'}")
    print(f"{'='*60}\n")

    sent_count = 0
    for i, job in enumerate(jobs, 1):
        email = job.get("apply_email", "")
        company = job.get("company", "Unknown")
        role = job.get("title", "Developer")

        if not email:
            print(f"[{i}/{len(jobs)}] SKIP {company} — no email")
            continue

        # Dedup check
        if email in sent_log:
            print(f"[{i}/{len(jobs)}] SKIP {company} — already sent to {email}")
            continue

        print(f"\n[{i}/{len(jobs)}] Processing: {role} @ {company} -> {email}")

        # Generate filenames
        safe_name = "".join(c if c.isalnum() else "_" for c in f"{company}_{role}").lower()[:50]
        cv_tex = CV_DIR / f"main_{safe_name}.tex"
        cover_tex = COVER_DIR / f"cover_{safe_name}.tex"

        # Generate tex files
        generate_cv_tex(job, cv_tex)
        generate_cover_tex(job, cover_tex)
        print(f"  Generated: {cv_tex.name}, {cover_tex.name}")

        # Compile
        cv_pdf = compile_cv(cv_tex)
        cover_pdf = compile_cover(cover_tex)

        if not cv_pdf.exists():
            print(f"  [ERROR] CV PDF not generated, skipping")
            continue
        if not cover_pdf.exists():
            print(f"  [ERROR] Cover PDF not generated, skipping")
            continue

        print(f"  Compiled: {cv_pdf.name} ({cv_pdf.stat().st_size//1024}KB), {cover_pdf.name} ({cover_pdf.stat().st_size//1024}KB)")

        if args.dry_run:
            print(f"  -> DRY RUN (not sent)")
            continue

        # Send
        try:
            send_application(email, cv_pdf, cover_pdf, job)
            sent_log[email] = {
                "company": company,
                "role": role,
                "date": time.strftime("%Y-%m-%d %H:%M"),
            }
            save_sent_log(sent_log)
            sent_count += 1
            print(f"  -> SENT ({sent_count} total)")
        except Exception as e:
            print(f"  [ERROR] Send failed: {e}")
            continue

        # Rate limiting
        if i < len(jobs) and sent_count > 0:
            delay_secs = random.randint(args.delay * 60, args.delay * 60 + 120)
            print(f"  Waiting {delay_secs//60}m {delay_secs%60}s...")
            time.sleep(delay_secs)

    print(f"\n{'='*60}")
    print(f"DONE — {sent_count} applications sent")
    print(f"{'='*60}")


if __name__ == "__main__":
    main()
